/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const NButton: typeof import('naive-ui')['NButton']
  const NConfigProvider: typeof import('naive-ui')['NConfigProvider']
  const NDrawer: typeof import('naive-ui')['NDrawer']
  const NDrawerContent: typeof import('naive-ui')['NDrawerContent']
  const NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
  const NMessageProvider: typeof import('naive-ui')['NMessageProvider']
  const useDialog: typeof import('naive-ui')['useDialog']
  const useLoadingBar: typeof import('naive-ui')['useLoadingBar']
  const useMessage: typeof import('naive-ui')['useMessage']
  const useNotification: typeof import('naive-ui')['useNotification']
}
